db.url=jdbc:mariadb://localhost:3306/smartfight?serverTimezone=UTC&characterEncoding=UTF-8
db.user=root
db.password=

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=teamsmartfight@gmail.com
mail.smtp.password=uucxnpkizyclppsr
mail.from=teamsmartfight@gmail.com

symfony.base.url=http://localhost:8001

upload.dir=C:/Users/ahmed/OneDrive/Desktop/pr/Smartfight/public/uploads
deepseek.api.key=sk-23d74dc6f4f14f5d8020ee22ff1939b4
deepseek.api.url=https://api.deepseek.com/v1

google.client.id=147498646326-qguh1dagi0mkrhn4sllh5cbu46lbn5rt.apps.googleusercontent.com
google.client.secret=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
